### ISSUE TITLE
坐标偏移问题

### ISSUE THREAD

**Issue by huojianzhatian** [longxiaofei/dianping#1]
感谢您的分享，为我做研究提供了很大的帮助，请问DianpingComment类里面的    font_size = 14 与 start_y两个全局变量是怎么定下来的呢

**Comment by longxiaofei** [comment]
font_size，在svg里的style里有。
start_y，通过修改偏移值，发现svg上下两个相邻字的y值与各自的y偏移相减等于同一个数(start_y)。
